name: FPC
version: '${project.version}'
main: nr.FPC
api-version: '1.20'
commands:
  fly:
    usage: /fly
  pvp:
    usage: /pvp
  rtp:
    usage: /rtp
  lockchest:
    usage: /lockchest
  tpa:
    usage: /tpa